baseURL: https://xeniahuber.netlify.app/
languageCode: en-us
title: Xenia Katharina Huber
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      LEARN ABOUT MY LIFE & GET IN TOUCH
    title: HELLO STRANGER, WELCOME TO XENIA'S WORLD
    image: 'banner.jpg'
  blog: {}
  contact:
    address:
     - city: London
       country: United Kingdom
       street: Regent's Park, NW1 4SA
       title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: 
        title: Please use contact form
    enable: yes
    phone:
      - phone: 
        title: Write me a message
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  footer:
    copyright: Xenia
    enable: yes
    quicklinks:
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/xenia_katharina
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/xenia-huber-598072111/?originalSubdomain=ch
  image: 'mongolia.jpg'
  name: Xenia Huber
  navigation:
    links:
      - name: Home
        url:
      - name: CV
        url: blogs/Xenia Huber_CV.pdf
      - name: Data Analytics & Visualisation
        url: projects/analytics_visualisation
      - name: Women for Women
        url: projects/women_for_women
      - name: ISC Alumni 
        url: projects/isc_alumni
      - name: Bachelor's Thesis
        url: blogs/Thesis.pdf
      - name: My Life in a Nutshell
        url: blogs
    menu: Menu
    title: Home
  two:
    title: My Life in a Nutshell
    url: blogs
  tiles:
    enable: yes
    showcase:
      - image: headshot.jpg
        subtitle: Learn about my Professional Experience
        title: CV
        url: blogs/Xenia Huber_CV.pdf
      - image: mongolia.jpg
        subtitle: Applied Statistics
        title: Data Analytics & Visualization
        url: projects/analytics_visualisation
      - image: w4wlogo.jpg
        subtitle: Head of Community
        title: Women for Women (1-on-1 Mentoring)
        url: projects/women_for_women
      - image: alumnilogo.jpg
        subtitle: Member of the Alumni Committe
        title: ISC Alumni
        url: projects/isc_alumni
      - image: unisg.jpg
        subtitle: Mind the gap! A multi case study analysis
        title: Bachelor's Thesis
        url: blogs/Thesis.pdf
      - image: dolsonne.jpg
        subtitle: Impressions of my free time
        title: My life in a Nutshell
        url: blogs
 
