baseURL: https://xeniahuber.netlify.app/
languageCode: en-us
title: Xenia Katharina Huber
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      LEARN ABOUT MY LIFE & ASK ME A QUESTION.
    title: HELLO STRANGER, WELCOME TO MY WORLD
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 88A York Street (W1H1QT)
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: xenia.huber@icloud.com
        title: Email
    enable: yes
    phone:
      - phone: +41 79 961 06 60
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Xenia
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
#        label: Twitter
 #       url: https://www.twitter.com
  #    - icon: fa-facebook
   #     label: Facebook
    #    url: https://www.facebook.com/XeniaHuber
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/xenia_katharina
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/LADYEX
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/xenia-huber-598072111/?originalSubdomain=ch
  image: ''
  name: Xenia Huber
  navigation:
  #  button1:
   #   - name: Get Started
    #    url: blogs
    #button2:
     # - name: Log In
      #  url: '#'
    links:
      - name: Home
        url
      - name: My Story
        url: blogs/my_story
      - name: My previous Work
        url: blogs/
      - name: Women for Women
        url: blogs/women_for_women
      - name: ISC Alumni 
        url: blogs/isc_alumni
    #  - name: Blogs
     #   url: blogs
      #- name: Generic Blog
       # url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Everything you need to know about me
        title: My Story
        url: blogs/my_story
      - image: pic02.jpg
        subtitle: Data Analytics & Visualization
        title: Previous Work
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Sign up for your personal1-to-1 mentoring
        title: Women for Women
        url: blogs/women_for_women
      - image: pic04.jpg
        subtitle: Member of Alumni Committe
        title: ISC Alumni
        url: blogs/isc_alumni
      #- image: pic05.jpg
      #  subtitle: Ipsum Dolor Sit Amet
       # title: Consequat
      #  url: blogs/ipsum
      #- image: pic06.jpg
       # subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
