baseURL: https://xeniahuber.netlify.app/
languageCode: en-us
title: Xenia Katharina Huber
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      LEARN ABOUT MY LIFE & GET IN TOUCH
    title: HELLO STRANGER, WELCOME TO MY WORLD
    image: 'banner.jpg'
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 88A York Street (W1H1QT)
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: xenia.huber@icloud.com
        title: Email
    enable: yes
    phone:
      - phone: +41 79 961 06 60
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Xenia
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
#        label: Twitter
 #       url: https://www.twitter.com
  #    - icon: fa-facebook
   #     label: Facebook
    #    url: https://www.facebook.com/XeniaHuber
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/xenia_katharina
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/LADYEX
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/xenia-huber-598072111/?originalSubdomain=ch
  image: 'mongolia.jpg'
  name: Xenia Huber
  navigation:
  #  button1:
   #   - name: Get Started
    #    url: blogs
    #button2:
     # - name: Log In
      #  url: '#'
    links:
      - name: Home
        url:
      - name: My Story
        url: blogs/my_story
      - name: CV
        url: blogs/Xenia Huber_CV.pdf
    #  - name: My previous Work
    #    url: blogs/
      - name: Women for Women
        url: blogs/women_for_women
      - name: ISC Alumni 
        url: blogs/isc_alumni
    #  - name: Blogs
     #   url: blogs
      #- name: Generic Blog
       # url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: mongolia.jpg
        subtitle: My Life in a Nutshell
        title: Xenia Katharina Huber
        url: blogs/my_story
      - image: headshot.jpg
        subtitle: Learn about my Professional Experience
        title: CV
        url: blogs/Xenia Huber_CV.pdf
      - image: mongolia.jpg
        subtitle: Data Analytics & Visualization
        title: Previous Work
        url: blogs/tempus
      - image: w4wlogo.jpg
        subtitle: Head of Community
        title: Women for Women (1-on-1 Mentoring)
        url: blogs/women_for_women
      - image: alumnilogo.jpg
        subtitle: Member of the Alumni Committe
        title: ISC Alumni
        url: blogs/isc_alumni
      - image: unisg.jpg
        subtitle: Mind the gap! A multi case study analysis
        title: Bachelor's Thesis
        url: blogs/Thesis.pdf
      #- image: pic06.jpg
       # subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
   # subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
    #  \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
     # condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
    #  pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
     # Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
    #  amet pharetra et feugiat tempus."
    title: My Life in a Nutshell
    url: blogs
